.Dd June 23, 2026
.Dt PHDIINFO 1
.Os
.Sh NAME
.Nm phdiinfo
.Nd determines information about a Parallels Hard Disk image file
.Sh SYNOPSIS
.Nm phdiinfo
.Op Fl hvV
.Ar source
.Sh DESCRIPTION
.Nm phdiinfo
is a utility to determine information about a Parallels Hard Disk image file
.Pp
.Nm phdiinfo
is part of the
.Nm libphdi
package.
.Nm libphdi
is a library to access the Parallels Hard Disk image (PHDI) format
.Pp
.Ar source
is the source image disk descriptor file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# phdiinfo DiskDescriptor.xml
phdiinfo 20151220
.sp
Parallels Hard Disk image information:
	Media size:		536870912 bytes
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libphdi/issues
.Sh COPYRIGHT
Copyright (C) 2015-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
