language: c
env:
  global:
   # Encrypted COVERITY_SCAN_TOKEN
   - secure: "e1ljg07ncCLmNm8uQqnS3mo4ce+fUFEM8A+dgrGU3D1KaVZaYCfxHUHYD+phjRnw4URbbfVS/D4etgnDa17ed0Hkdm4mFBEW/VL73BdF7ufI0pHrG/hEvSr7ugxhDETqcftpNarLuYE+TuntPZilfQ7E1kckSgLXXFEOH7qPVIarEARhaUEIryQXnxMTFZbZ/dWG+mIL4OYy6+j9fDxavFzn3UF+FrEGpDaJ4GtCVBmMomhkdreDSp/2EsjmQeifMKeO1/v2nRgdRERKc1ir62mUB48YjWt0xCQTyhKI5vLZGaSsE8mCRVagvYWjelcrHvAiE+UXVm2EPEQJf6+BEJbnL4dUwERg+WQgGPJ/H4lwi9eDE8nXsbGGpn2hRpElHbueu2UhbyQ/uW2iTqy+BRr2/r5ZaMlyRLABEFw8DitGbeaQV5Qul1Fh4lpZsQkr+JfQMTJzkP4EcmMIIH6GCRrSkAs0XV0KTcA+kSqRIHufgoZf8CVThKIQbWvKFrs0ChU/qwcsUxX1dsPTY/8AhBdNIQ69YId/PLcVvO2HRtfM9C1YZ5/nxJFnLr0dPHlJL5AwOP8f/UykuafjvD+0KCVKFNOoYXNfSdfFYnD38rM72RJt1Knw/fycwU0JR91rPg4FlcNuEtidRQcs5QbLvs3/6iufGop9R6b6H12u05s="
matrix:
  include:
  - name: "Coverity"
    env:
    - CONFIGURE_OPTIONS=""
    - TARGET="coverity"
    compiler: clang
    os: linux
    dist: xenial
    sudo: required
    group: edge
    addons:
      coverity_scan:
        project:
          name: "libyal/libphdi"
          description: "Build submitted via Travis CI"
        notification_email: joachim.metz@gmail.com
        build_command_prepend: "./synclibs.sh && ./autogen.sh && ./configure"
        build_command: "make -j4"
        branch_pattern: master
  - name: "Linux with clang"
    env:
    - CONFIGURE_OPTIONS=""
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-clang"
    compiler: clang
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc"
    env:
    - CONFIGURE_OPTIONS=""
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc and wide character type (wchar_t) support"
    env:
    - CONFIGURE_OPTIONS="--enable-wide-character-type"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-wide-character-type"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc without optimization"
    env:
    - CONFIGURE_OPTIONS="--enable-shared=no --enable-wide-character-type"
    - CFLAGS="--coverage -O0"
    - CPPFLAGS="-DOPTIMIZATION_DISABLED"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-no-optimization"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc and Python module"
    env:
    - CONFIGURE_OPTIONS="--enable-python"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-python"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc and Python 2 module"
    env:
    - CONFIGURE_OPTIONS="--enable-python2"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - PYTHON_VERSION=2
    - TARGET="linux-gcc-python2"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc and Python 3 module"
    env:
    - CONFIGURE_OPTIONS="--enable-python3"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - PYTHON_VERSION=3
    - TARGET="linux-gcc-python3"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc and Python 2 module (setup.py)"
    env:
    - TARGET="linux-gcc-python-setup-py"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
    python: 2.7
  - name: "Linux with gcc and Python 3 module (setup.py)"
    env:
    - TARGET="linux-gcc-python-setup-py"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
    python: 3.4
  - name: "Linux with gcc and shared libraries"
    env:
    - CONFIGURE_OPTIONS=""
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-shared"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc, shared libraries and wide character type (wchar_t) support"
    env:
    - CONFIGURE_OPTIONS="--enable-wide-character-type"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-shared-wide-character-type"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Linux with gcc and static executables support"
    env:
    - CONFIGURE_OPTIONS="--enable-static-executables"
    - CFLAGS="--coverage"
    - LDFLAGS="--coverage"
    - TARGET="linux-gcc-static-executables"
    compiler: gcc
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Mac OS with clang"
    env:
    - CONFIGURE_OPTIONS=""
    - TARGET="macos-clang"
    compiler: clang
    os: osx
    osx_image: xcode8.3
  - name: "Mac OS with gcc"
    env:
    - CONFIGURE_OPTIONS=""
    - TARGET="macos-gcc"
    compiler: gcc
    os: osx
    osx_image: xcode8.3
  - name: "Mac OS with gcc and Python module"
    env:
    - CONFIGURE_OPTIONS="--enable-python"
    - TARGET="macos-gcc-python"
    compiler: gcc
    os: osx
    osx_image: xcode8.3
  - name: "Mac OS with gcc and Python 2 module"
    env:
    - CONFIGURE_OPTIONS="--enable-python2"
    - PYTHON_VERSION=2
    - TARGET="macos-gcc-python2"
    compiler: gcc
    os: osx
    osx_image: xcode8.3
  - name: "Mac OS with gcc and Python 2 module (setup.py)"
    env:
    - TARGET="macos-gcc-python-setup-py"
    compiler: gcc
    os: osx
    osx_image: xcode8.3
  - name: "Mac OS gcc and pkgbuild"
    env:
    - CONFIGURE_OPTIONS="--disable-dependency-tracking --prefix=/usr/local --enable-python --with-pyprefix"
    - TARGET="macos-gcc-pkgbuild"
    compiler: gcc
    os: osx
    osx_image: xcode8.3
before_install:
  - if test ${TRAVIS_OS_NAME} = "linux"; then
      sudo apt-get update && sudo apt-mark hold mysql-server-5.7 && sudo apt-get --fix-missing -o Dpkg::Options::="--force-confold" upgrade -y --allow-unauthenticated && sudo apt-get install -y autopoint libfuse-dev;
    elif test ${TRAVIS_OS_NAME} = "osx"; then
      brew update && brew install gettext gnu-sed && brew link --force gettext;
      brew tap homebrew/cask && brew cask install osxfuse;
    fi
  - if test ${TARGET} = "coverity"; then
      echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-;
    fi
install:
  - if test ${TRAVIS_OS_NAME} = "osx"; then
      export SED="/usr/local/bin/gsed";
    fi
  - ./synclibs.sh --use-head && ./autogen.sh
  - if test ${TARGET} = "linux-gcc-shared" || test ${TARGET} = "linux-gcc-shared-wide-character-type"; then
      ./configure > /dev/null && make > /dev/null && ./syncsharedlibs.sh --use-head;
    fi
  - if test -x "synctestdata.sh"; then
      ./synctestdata.sh;
    fi
script:
  - if test ${TRAVIS_OS_NAME} = "linux"; then
      export PATH=$(echo $PATH | tr ":" "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s/::/:/g");
    fi
  - if test ${TARGET} = "linux-gcc-python-setup-py" || test ${TARGET} = "macos-gcc-python-setup-py"; then
      ./configure ${CONFIGURE_OPTIONS} && make > /dev/null && python ./setup.py build;
    elif test ${TARGET} != "coverity"; then
      ./configure ${CONFIGURE_OPTIONS} && make > /dev/null && make check CHECK_WITH_STDERR=1;
      if test $? -ne 0 && test -f tests/test-suite.log; then
        cat tests/test-suite.log;
      fi;
      if test ${TARGET} = "macos-gcc-pkgbuild"; then
        VERSION=`sed '5!d; s/^ \[//;s/\],$//' configure.ac` &&
        make install DESTDIR=${PWD}/osx-pkg &&
        mkdir -p ${PWD}/osx-pkg/usr/share/doc/libphdi &&
        cp AUTHORS COPYING NEWS README ${PWD}/osx-pkg/usr/share/doc/libphdi &&
        pkgbuild --root osx-pkg --identifier com.github.libyal.libphdi --version ${VERSION} --ownership recommended ../libphdi-${VERSION}.pkg;
      fi
    fi
after_success:
  - if test ${TARGET} = "linux-gcc-no-optimization"; then
      curl -o codecov.sh -s https://codecov.io/bash && sed 's/ -execdir / -exec /' -i ./codecov.sh && /bin/bash ./codecov.sh -n ${TARGET} -y .codecov.yml;
    fi
